/**
 * POST /api/projects/:id/name — record the chosen name and tagline.
 *
 * A human decision, never inferred. No model is called: the candidates were already
 * generated by the naming stage, and this only records which one was picked. The engine
 * validates the pick against what was actually offered, so a name nothing in the
 * pipeline reasoned about cannot end up in the Brand OS.
 *
 * Mirrors the strategy selection endpoint deliberately — the two are the same kind of act
 * and should look the same to whoever is calling them.
 */
import { applyDelta, selectName } from 'brandstate';
import { SelectNameBody } from '@/lib/api/contracts';
import type { SelectNameResponse } from '@/lib/api/contracts';
import { BadRequestError, handle, ok, parseBody } from '@/lib/api/respond';
import { requireUser } from '@/lib/auth/session';
import { loadBrandState, saveBrandState, toProjectSummary, getProject } from '@/lib/db/projects';

export const runtime = 'nodejs';

export async function POST(request: Request, context: { params: Promise<{ id: string }> }) {
  return handle<SelectNameResponse>(async () => {
    const { id } = await context.params;
    const user = await requireUser();
    const body = await parseBody(request, SelectNameBody);

    const state = await loadBrandState(id, user.id);

    if (state.naming.candidates.length === 0) {
      throw new BadRequestError(
        'No name candidates exist yet. Run POST /api/projects/:id/identity first — there ' +
          'is nothing to choose between.',
      );
    }

    // Throws NameNotOfferedError if the pick was not on offer, which the error handler
    // turns into a 400 listing what was.
    const naming = selectName(state.naming, { name: body.name, tagline: body.tagline });
    const saved = await saveBrandState(id, user.id, applyDelta(state, 'naming', naming));

    return ok({
      naming: saved.naming,
      project: toProjectSummary(await getProject(id, user.id)),
    });
  });
}
