// ESLint flat config.
//
// Flat config rather than `next lint`, which is deprecated in Next 15 and removed in 16.
// Run with `npm run lint`.
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  {
    // Build output and generated code are not ours to lint.
    // next-env.d.ts is generated by Next and uses triple-slash references by design.
    ignores: [
      '.next/**',
      '.next-dev/**',
      'node_modules/**',
      'src/generated/**',
      'prisma/**',
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // A CommonJS config file cannot use `import`; require() is correct there.
    files: ['*.config.js', 'postcss.config.js', 'tailwind.config.js'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    rules: {
      // The engine's structured-output boundary genuinely deals in `unknown` and casts
      // at the edges; this is enforced by Zod at runtime rather than by the type system.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Unused args prefixed with _ are a deliberate signal, not an oversight.
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
];

export default config;
